local_backend: true

backend:
  name: test-repo

media_folder: "src/assets"
public_folder: "/src/assets"

collections:
  - name: "doctors"
    label: "Doctors"
    files:
      - label: "Doctors Data"
        name: "doctors"
        file: "src/data/doctors.json"
        fields:
          - label: "Doctors"
            name: "doctors"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Specialization", name: "specialization", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Experience", name: "experience", widget: "string" }
              - { label: "Fee", name: "fee", widget: "number" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Qualifications", name: "qualifications", widget: "string" }
              - { label: "Availability", name: "availability", widget: "string" }
